[package]
name = "rust_book"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = { version = "0.4.1", features = [] }
regex = "1.10.2"
matches = "0.1.10"
itertools = "0.12.0"
colorful = "0.2.2"
